### ISSUE TITLE
Add options for removing git commit hash and newline

### ISSUE THREAD

**Issue by collinksmith** [yardnsm/blox-zsh-theme#5]
I like this theme a lot, just a couple suggestions for more options. I think it would be nice to have the option to remove the commit hash and the newline between prompts.

**Comment by yardnsm** [comment]
Glad you liked it :)

I've added the option to hide the commit hash in b5463e1dbd6296d991b14801dadfded375c10c9b, simply set the following:

```zsh
BLOX_BLOCK__GIT_COMMIT_SHOW=false
```

Regarding the newline between prompts, you can set the following:

```zsh
BLOX_CONF__PROMPT_PREFIX=''
```
