### ISSUE TITLE
BLOX_CONF__PROMPT_PREFIX can only be disabled via unset

### ISSUE THREAD

**Issue by wingrunr21** [yardnsm/blox-zsh-theme#6]
The changes introduced in #3 makes it such that `BLOX_CONF__PROMPT_PREFIX` can only be disabled by unsetting it after sourcing `blox.zsh`. The [expansion done here](https://github.com/yardnsm/blox-zsh-theme/blob/master/blox.zsh#L42) means any null/empty value for that variable will be replaced with `\n`, effectively meaning you cannot disable the prompt prefix.

**Comment by yardnsm** [comment]
First of all, thanks for submitting this issue! Sorry for the delay, these two weeks have been a bit busy.

This issue has been fixed in #7.

**Comment by wingrunr21** [comment]
No problem! Thanks for the fix!
